<a href="https://colab.research.google.com/github/sparsh-tekriwal/Image-Recognition-Dogs-vs-Cats/blob/master/Image%20Classification%20using%20PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# !wget https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip -P 'drive/My Drive/PetImages'

In [3]:
# !unzip 'drive/My Drive/PetImages/kagglecatsanddogs_3367a.zip' -d 'drive/My Drive/'

In [12]:
# !cp /content/training_data.npy 'drive/My Drive/PetImages'

In [4]:
import os
import cv2
import numpy as np
from tqdm import tqdm

In [5]:
REBUILD_DATA = True

In [ ]:
class DogsVSCats():
  IMG_SIZE = 50
  CATS = "PetImages/Cat"
  DOGS = "PetImages/Dog"
  LABELS = {CATS: 0, DOGS: 1}
  training_data = []
  catcount = 0
  dogcount = 0

  def make_training_data(self):
    # Iterating through Cats and Dogs directories
    for label in self.LABELS:
      print(label)
      # Iterating through contents of each directory along with a progress bar
      for f in tqdm(os.listdir(label)):
        try:
          # joining file name to path
          path = os.path.join(label, f)
          #reading image file and converting to grayscale as my hypothesis is color doesn't matter while differenciating between cats and dogs. 
          # And we gotta simplify for efficient NN computation
          img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
          # I have defined this parmater for the class
          img = cv2.resize(img, (self.IMG_SIZE, self.IMG_SIZE))
          # converting labels to a one hot format
          self.training_data.append([np.array(img), np.eye(2)[self.LABELS[label]]])

          # Counting number of data points in each class
          if label == self.CATS:
            self.catcount +=1
          elif label == self.DOGS:
            self.dogcount +=1
        
        except Exception as e:
          print("We have an issue with this dog/cat image: " + str(e))
    # Shuffling the ingested data so that they are evenly distributed
    # No reassignment requiremnt for this numpy function
    np.random.shuffle(self.training_data)
    # Saving data so that I don't need to import it do this computation again
    np.save("training_data.npy", self.training_data)
    print("Cats: ", self.catcount)
    print("Dogs: ", self.dogcount)

if REBUILD_DATA:
  dogvcats = DogsVSCats()
  dogvcats.make_training_data()

In [10]:
training_data = np.load("training_data.npy", allow_pickle = True)


In [15]:
training_data[:5]

array([[array([[150, 169, 160, ..., 145, 142, 149],
       [165, 139, 158, ..., 139, 135, 150],
       [158, 141, 137, ..., 135, 156, 152],
       ...,
       [146, 193, 201, ..., 199, 109,  99],
       [158, 168, 192, ..., 166, 168, 182],
       [145, 143, 134, ..., 166, 221, 101]], dtype=uint8),
        array([0., 1.])],
       [array([[21, 21, 22, ..., 41, 38, 36],
       [21, 23, 23, ..., 45, 43, 40],
       [22, 24, 25, ..., 51, 48, 44],
       ...,
       [62, 47, 61, ..., 22, 20, 19],
       [61, 67, 57, ..., 24, 25, 18],
       [74, 62, 54, ..., 32, 28, 21]], dtype=uint8),
        array([1., 0.])],
       [array([[194, 196, 198, ...,  76,  75,  73],
       [200, 200, 200, ...,  74,  74,  76],
       [198, 198, 198, ...,  73,  74,  98],
       ...,
       [131, 128, 140, ..., 153, 156, 153],
       [142, 137, 136, ..., 154, 149, 148],
       [138, 134, 138, ..., 150, 153, 158]], dtype=uint8),
        array([0., 1.])],
       [array([[127, 128, 129, ..., 177, 169, 164],
       [1